// Auto-generated by zimic.
// NOTE: Do not manually edit this file. Changes will be overridden.

import type {
  HttpSchema,
  HttpSearchParamsSerialized,
  HttpStatusCode,
  MergeHttpResponsesByStatusCode,
} from 'zimic/http';

export type LocationSchema = HttpSchema.Paths<{
  '/cities': {
    /** Buscar cidades */
    GET: LocationOperations['cities/search'];
  };
  '/cities/distances': {
    /** Obter distância entre cidades */
    GET: LocationOperations['cities/distances/get'];
  };
}>;

export interface LocationComponents {
  schemas: {
    City: {
      /**
       * @description O identificador da cidade
       * @example aGVyZTpjbTpuYW1lZHBsYWNlOjIzMDMwNjEy
       */
      id: string;
      /**
       * @description O nome da cidade
       * @example São Paulo
       */
      name?: string;
      /** @description O estado da cidade */
      state?: {
        /**
         * @description O nome do estado
         * @example São Paulo
         */
        name?: string;
        /**
         * @description O código do estado
         * @example SP
         */
        code?: string;
      };
      /** @description O país da cidade */
      country?: {
        /**
         * @description O nome do país
         * @example Brasil
         */
        name?: string;
        /**
         * @description O código do país
         * @example BRA
         */
        code?: string;
      };
    };
    Distance: {
      /**
       * Format: double
       * @description A distância em quilômetros (km)
       * @example 145.3
       */
      kilometers: number;
    };
    ValidationError: {
      /**
       * @description A mensagem de erro
       * @example Entrada inválida
       */
      message: string;
      /** @description Os problemas de validação */
      issues?: {
        [key: string]: any;
      }[];
    };
    NotFoundError: {
      /**
       * @description A mensagem de erro
       * @example Item não encontrado
       */
      message: string;
    };
    InternalServerError: {
      /**
       * @description A mensagem de erro
       * @example Erro inesperado
       */
      message: string;
    };
  };
}

export interface LocationOperations {
  'cities/search': HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        /** @description O nome da cidade para busca */
        query: string;
      }>;
    };
    response: MergeHttpResponsesByStatusCode<
      [
        {
          /** @description Cidades encontradas */
          200: {
            body: LocationComponents['schemas']['City'][];
          };
          /** @description Erro de validação */
          400: {
            body: LocationComponents['schemas']['ValidationError'];
          };
        },
        {
          /** @description Erro inesperado */
          [StatusCode in HttpStatusCode.ServerError]: {
            body: LocationComponents['schemas']['InternalServerError'];
          };
        },
      ]
    >;
  }>;
  'cities/distances/get': HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        /**
         * @description O identificador da cidade de origem
         * @example aGVyZTpjbTpuYW1lZHBsYWNlOjIzMDMwNjEy
         */
        originCityId: string;
        /**
         * @description O identificador da cidade de destino
         * @example aGVyZTpjbTpuYW1lZHBsYWNlOjIzMDM2NjI4
         */
        destinationCityId: string;
      }>;
    };
    response: MergeHttpResponsesByStatusCode<
      [
        {
          /** @description Distância encontrada */
          200: {
            body: LocationComponents['schemas']['Distance'];
          };
          /** @description Erro de validação */
          400: {
            body: LocationComponents['schemas']['ValidationError'];
          };
          /** @description Uma ou ambas as cidades não encontradas */
          404: {
            body: LocationComponents['schemas']['NotFoundError'];
          };
        },
        {
          /** @description Erro inesperado */
          [StatusCode in HttpStatusCode.ServerError]: {
            body: LocationComponents['schemas']['InternalServerError'];
          };
        },
      ]
    >;
  }>;
}
